version: "3"

services:
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres

  backend:
    extends:
      file: docker-compose.base.yml
      service: backend
    environment:
      - POSTGRES_HOST=host.docker.internal
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    depends_on:
      backend:
        condition: service_healthy
    build: "./admin-ui"
    platform: linux/amd64
    # Un-comment if using Apple silicon
    #platform: linux/arm64
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - app_network
    volumes:
      - ${PWD}/frontend.env:/usr/share/nginx/html/.env

networks:
  app_network:
    driver: bridge

volumes:
  tmp:
