nodeLinker: node-modules

npmScopes:
  tableflowhq:
    npmAlwaysAuth: true
    npmAuthToken: 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
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-3.6.0.cjs
